//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogIT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogITEntities : DbContext
    {
        public BlogITEntities()
            : base("name=BlogITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogPost> BlogPost { get; set; }
        public virtual DbSet<Bookmark> Bookmark { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CommentReply> CommentReply { get; set; }
        public virtual DbSet<Follow> Follow { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<PostLike> PostLike { get; set; }
        public virtual DbSet<PostTag> PostTag { get; set; }
        public virtual DbSet<ReportBlog> ReportBlog { get; set; }
        public virtual DbSet<ReportComment> ReportComment { get; set; }
        public virtual DbSet<ReportCommentReply> ReportCommentReply { get; set; }
        public virtual DbSet<ReportUser> ReportUser { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
