//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTag
    {
        public int PostID { get; set; }
        public int TagID { get; set; }
        public int PostTagID { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
