//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportUser
    {
        public int ReportID { get; set; }
        public Nullable<int> ReportedUserID { get; set; }
        public Nullable<int> ReporterID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> ReportedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
